### ISSUE TITLE
Startup crash

### ISSUE THREAD

**Issue by DevTimur** [p455w0rd/WirelessInterfaceTerminal#1]
Hi.
I get crash with your mod in, I thought it's others mod fault so reported an issue.
But apparently it's your WIT mod fault
https://github.com/SilentChaos512/ScalingHealth/issues/178
Can you please deal with it?

**Comment by DevTimur** [comment]
P.S. I had issue with Industrialcraft aswell, and some other mod, don't remember.
Can you check this aswell?

**Comment by SilentChaos512** [comment]
No, this needs to be fixed on my end. A mod ID isn't something that can be easily changed.

**Comment by p455w0rd** [comment]
It's simple enough..DataFixers can (for the most part) resolve this. I will be merging all of the terminals into a single mod when I get time though, so modid will be changing at that point anyway..thanks for working on this tho @SilentChaos512
